theme: minima
title: title
author: Kevin Dang
email: kdang4@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
idk

# social links
twitter_username: n0
github_username:  n0
show_excerpts: true # set to false to remove excerpts on the homepage
